Enable spark logging on executors
Previously, executor logs would fail with:
java.io.FileNotFoundException: /mnt/var/log/spark/spark.log (Permission denied)

Which caused the executor logs to not write.

This change will make them available, and then available in s3.